[package]
authors = ["Hugo Ledoux <h.ledoux@tudelft.nl>"]
name    = "startin"
version = "0.1.7"
edition = "2018"


[dependencies]
startin = "0.4.7"


[dependencies.pyo3]
version = "0.8.2"
features = ["extension-module"]


[lib]
name = "startin"
crate-type = ["cdylib"]


[package.metadata.maturin]
requires-dist = ["toml==0.10.0"]